// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbkt-G2VDagfepNysgp98vIn-DYbk3jSA',
    appId: '1:807516873313:web:596714936e27c18a58c020',
    messagingSenderId: '807516873313',
    projectId: 'fes-connect-x',
    authDomain: 'fes-connect-x.firebaseapp.com',
    storageBucket: 'fes-connect-x.firebasestorage.app',
    measurementId: 'G-PSCCYPBFEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8riXJWzntBGxJY4Xrii5Wo5dIdA7OPEo',
    appId: '1:807516873313:android:c0c0547b4f270ebf58c020',
    messagingSenderId: '807516873313',
    projectId: 'fes-connect-x',
    storageBucket: 'fes-connect-x.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX31LenqOfqI0GAV5yQBs2qpYHLbexWcI',
    appId: '1:807516873313:ios:262e43033ec287ba58c020',
    messagingSenderId: '807516873313',
    projectId: 'fes-connect-x',
    storageBucket: 'fes-connect-x.firebasestorage.app',
    androidClientId: '807516873313-1sg2u71q26oug0hfj79em8ktl5snfvcp.apps.googleusercontent.com',
    iosClientId: '807516873313-7th3bph1ogud5itah3qs6kvtl0nsemb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.facultyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX31LenqOfqI0GAV5yQBs2qpYHLbexWcI',
    appId: '1:807516873313:ios:262e43033ec287ba58c020',
    messagingSenderId: '807516873313',
    projectId: 'fes-connect-x',
    storageBucket: 'fes-connect-x.firebasestorage.app',
    androidClientId: '807516873313-1sg2u71q26oug0hfj79em8ktl5snfvcp.apps.googleusercontent.com',
    iosClientId: '807516873313-7th3bph1ogud5itah3qs6kvtl0nsemb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.facultyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbkt-G2VDagfepNysgp98vIn-DYbk3jSA',
    appId: '1:807516873313:web:596714936e27c18a58c020',
    messagingSenderId: '807516873313',
    projectId: 'fes-connect-x',
    authDomain: 'fes-connect-x.firebaseapp.com',
    storageBucket: 'fes-connect-x.firebasestorage.app',
    measurementId: 'G-PSCCYPBFEQ',
  );
}
